---

# Prerequisite:
#   ssh access with root and password
#   ssh authentication key on local machine

- hosts: all
  vars_files:
    - ./credentials.yml

  vars:
    - ansible_user: "{{ ROOT_USER | default('debian') }}"
    - ansible_password: "{{ ROOT_PASSWORD }}"

  remote_user: debian

  tasks:

    - name: ensure sudo is installed - Debian
      become: true
      apt:
        name: sudo
      when: ansible_distribution == 'Debian'

    - name: ensure sudo is installed - CentOS & RHEL
      become: true
      yum:
        name: sudo
      when: ansible_distribution == 'CentOS' or ansible_distribution == "RedHat"

    - name: ensure user is present - Debian
      become: true
      user:
        name: chatbot_user
        append: yes
        groups: sudo, root, www-data
        password: "{{ USER_PASSWORD | password_hash('sha512') }}"
      when: ansible_distribution == 'Debian'

    - name: ensure user is present - CentOS & RHEL
      become: true
      user:
        name: chatbot_user
        append: yes
        groups: wheel, root
        password: "{{ USER_PASSWORD | password_hash('sha512') }}"
      when: ansible_distribution == 'CentOS' or ansible_distribution == "RedHat"
