---

- name: Install Prometheus Node Exporter

  hosts: all

  remote_user: chatbot_user

  vars_files:
    - ./credentials.yml

  vars:
    - nodeExporterVersion: '1.0.1'
    - nodeExporterUser: 'node_exporter_user'
    - nodeExporterGroup: 'node_exporter_group'
    - ansible_become_pass: "{{ USER_PASSWORD }}"

  tasks:
    - name: Creating node_exporter user group
      group: name="{{ nodeExporterGroup }}"
      become: yes

    - name: Creating node_exporter user
      user:
        name: "{{nodeExporterUser}}"
        group: "{{nodeExporterGroup}}"
        system: yes
        shell: "/sbin/nologin"
        comment: "{{nodeExporterUser}} nologin User"
        createhome: "no"
        state: present
      become: yes

    - name: Install prometheus node exporter
      unarchive:
        src: "https://github.com/prometheus/node_exporter/releases/download/v{{ nodeExporterVersion }}/node_exporter-{{ nodeExporterVersion }}.linux-amd64.tar.gz"
        dest: /tmp/
        remote_src: yes

    - name: Copy prometheus node exporter file to bin
      copy:
        src: "/tmp/node_exporter-{{ nodeExporterVersion }}.linux-amd64/node_exporter"
        dest: "/usr/local/bin/node_exporter"
        owner: "{{nodeExporterUser}}"
        group: "{{nodeExporterGroup}}"
        remote_src: yes
        mode: 0755
      become: yes

    - name: Delete node exporter tmp folder
      file:
        path: '/tmp/node_exporter-{{ nodeExporterVersion }}.linux-amd64'
        state: absent

    - name: Copy systemd init file
      become: yes
      copy:
        src: prometheus.node_exporter.init.service
        dest: /etc/systemd/system/node_exporter.service

    - name: Start node_exporter service
      become: yes
      systemd:
        daemon_reload: yes
        name: node_exporter
        state: started
        enabled: yes

    - name: Check if node exporter emits metrics
      uri:
        url: http://127.0.0.1:9100/metrics
        method: GET
        status_code: 200
