---

# Prerequisits: Launch prebook & debianserver (Back repo)


- name: Init server for Angular App

  hosts: localhost

  remote_user: fab_user

  vars:
    - userDir: '/home/fab_user'
    - appsDir: '/var/www'
    - angularDir: 'fabrique-chatbot-front'
    - ansible_become_pass: "{{ user_password }}"

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: 'yes'
        update_cache: 'yes'

    - name: Install required dependencies (nginx, node, npm, certbot ...)
      become: true
      apt:
        pkg:
          - nginx
          - openssl

    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes
      become: yes

    - name: remove old angular app
      file:
        path: '{{ appsDir }}/{{ angularDir }}/'
        state: absent
      become: yes

    - name: copy angular app
      copy:
        src: '{{ userDir }}/{{ angularDir }}/'
        dest: '{{ appsDir }}/{{ angularDir }}'
      become: yes
