---
- name: Init chatbot server

  hosts: localhost

  remote_user: fab_user

  vars_files:
    - ./vars.yml

  vars:
    - userDir: '/home/fab_user'
    - appsDir: '/var/www'
    - nestDir: 'fabrique-chatbot-back'
    - backDir: 'chatbot-back'
    - botDir: 'chatbot-template'
    - frontDir: 'chatbot-front'
    - ansible_become_pass: "{{ USER_PASSWORD }}"

  tasks:
    - name: Git chatbot-back
      become: yes
      git:
        repo: https://github.com/fabnumdef/chatbot-back.git
        dest: '{{ appsDir }}/{{ nestDir }}/chatbot/{{ backDir }}'

    - name: Git chatbot-front
      become: yes
      git:
        repo: https://github.com/fabnumdef/chatbot-front.git
        dest: '{{ appsDir }}/{{ nestDir }}/chatbot/{{ frontDir }}'
      register: pullFront

    - name: Git chatbot-template
      become: yes
      git:
        repo: https://github.com/fabnumdef/chatbot-template.git
        dest: '{{ appsDir }}/{{ nestDir }}/chatbot/{{ botDir }}'

    - name: npm install chatbot-front
      become: yes
      npm:
        path: '{{ appsDir }}/{{ nestDir }}/chatbot/{{ frontDir }}'
      register: installFront

    - name: npm install chatbot-front librairies
      become: yes
      npm:
        path: '{{ appsDir }}/{{ nestDir }}/chatbot/{{ frontDir }}/projects/ngx-rasa-webchat'
      register: installFront

    - name: npm build chatbot-front
      become: yes
      command:
        cmd: npm run build:prod
        chdir: '{{ appsDir }}/{{ nestDir }}/chatbot/{{ frontDir }}'
      when: pullFront.changed or installFront.changed
