---
- name: Création du répertoire git
  become: true
  ansible.builtin.file:
    path: '{{ appsDir }}/{{ gitDir }}'
    state: directory
    owner: '{{ script_user }}'
    mode: '775'

- name: Git chatbot-back
  ansible.builtin.git:
    repo: https://github.com/fabnumdef/chatbot-back.git
    dest: '{{ appsDir }}/{{ gitDir }}/{{ backDir }}'
    force: true
    version: '{{ backBranch }}'

- name: Git chatbot-front
  ansible.builtin.git:
    repo: https://github.com/fabnumdef/chatbot-front.git
    dest: '{{ appsDir }}/{{ gitDir }}/{{ frontDir }}'
    force: true
    version: '{{ frontBranch }}'

- name: Git chatbot-template
  ansible.builtin.git:
    repo: https://github.com/fabnumdef/chatbot-template.git
    dest: '{{ appsDir }}/{{ gitDir }}/{{ botDir }}'
    force: true
    version: '{{ botBranch }}'
