- name: create git dir
  become: true
  file:
    path: '{{ appsDir }}/{{ gitDir }}'
    state: directory
    mode: '755'

- name: Git chatbot-back
  git:
    repo: https://github.com/fabnumdef/chatbot-back.git
    dest: '{{ appsDir }}/{{ gitDir }}/{{ backDir }}'
    force: yes
    version: '{{ backBranch }}'
  when: updateBack

- name: Git chatbot-front
  git:
    repo: https://github.com/fabnumdef/chatbot-front.git
    dest: '{{ appsDir }}/{{ gitDir }}/{{ frontDir }}'
    force: yes
    version: '{{ frontBranch }}'
  register: pullFront
  when: updateFront

- name: Git chatbot-template
  git:
    repo: https://github.com/fabnumdef/chatbot-template.git
    dest: '{{ appsDir }}/{{ gitDir }}/{{ botDir }}'
    force: yes
    version: '{{ botBranch }}'
  when: updateRasa

- name: npm install chatbot-front
  npm:
    path: '{{ appsDir }}/{{ gitDir }}/{{ frontDir }}'
  when: updateFront and pullFront.changed

- name: npm install chatbot-front librairies
  npm:
    path: '{{ appsDir }}/{{ gitDir }}/{{ frontDir }}/projects/ngx-rasa-webchat'
  when: updateFront and pullFront.changed

- name: npm build chatbot-front
  command:
    cmd: npm run build:prod
    chdir: '{{ appsDir }}/{{ gitDir }}/{{ frontDir }}'
  when: updateFront and pullFront.changed
