- name: Changement de droits et de propriétaire pour le dossier www
  become: true
  file:
    path: '{{ appsDir }}'
    state: directory
    owner: '{{ ansible_user }}'
    mode: '775'

- name: Création du répertoire git
  become: true
  file:
    path: '{{ appsDir }}/{{ gitDir }}'
    state: directory
    owner: '{{ ansible_user }}'
    mode: '775'

- name: Git chatbot-back
  git:
    repo: https://github.com/fabnumdef/chatbot-back.git
    dest: '{{ appsDir }}/{{ gitDir }}/{{ backDir }}'
    force: yes
    version: '{{ backBranch }}'

- name: Git chatbot-front
  git:
    repo: https://github.com/fabnumdef/chatbot-front.git
    dest: '{{ appsDir }}/{{ gitDir }}/{{ frontDir }}'
    force: yes
    version: '{{ frontBranch }}'

- name: Git chatbot-template
  git:
    repo: https://github.com/fabnumdef/chatbot-template.git
    dest: '{{ appsDir }}/{{ gitDir }}/{{ botDir }}'
    force: yes
    version: '{{ botBranch }}'
