- name: change rights www dir
  become: true
  file:
    path: '{{ appsDir }}'
    state: directory
    owner: chatbot_user
    mode: '775'

- name: create git dir
  become: true
  file:
    path: '{{ appsDir }}/{{ gitDir }}'
    state: directory
    owner: chatbot_user
    mode: '775'

- name: Git chatbot-back
  git:
    repo: https://github.com/fabnumdef/chatbot-back.git
    dest: '{{ appsDir }}/{{ gitDir }}/{{ backDir }}'
    force: yes
    version: '{{ backBranch }}'

- name: Git chatbot-front
  git:
    repo: https://github.com/fabnumdef/chatbot-front.git
    dest: '{{ appsDir }}/{{ gitDir }}/{{ frontDir }}'
    force: yes
    version: '{{ frontBranch }}'

- name: Git chatbot-template
  git:
    repo: https://github.com/fabnumdef/chatbot-template.git
    dest: '{{ appsDir }}/{{ gitDir }}/{{ botDir }}'
    force: yes
    version: '{{ botBranch }}'

- name: npm install chatbot-front
  npm:
    path: '{{ appsDir }}/{{ gitDir }}/{{ frontDir }}'

- name: npm install chatbot-front librairies
  npm:
    path: '{{ appsDir }}/{{ gitDir }}/{{ frontDir }}/projects/ngx-rasa-webchat'

- name: npm build chatbot-front
  command:
    cmd: npm run build:prod
    chdir: '{{ appsDir }}/{{ gitDir }}/{{ frontDir }}'
