---
- name: Génération d'un Chatbot
  hosts: all
  remote_user: debian
  vars_files:
    - roles/vars/main.yml

  vars:
    - ansible_user: "{{ ROOT_USER }}"
    - ansible_password: "{{ ROOT_PASSWORD }}"
    - ansible_become_pass: "{{ ROOT_PASSWORD }}"

  roles:
    - chatbotPrebook
