---
- name: Configuration du Backoffice nouvellement crée
  hosts: all
  remote_user: chatbot_user
  vars_files:
    - roles/vars/main.yml

  roles:
    - backofficeConfiguration

  vars:
    - ansible_password: "{{ USER_PASSWORD }}"
