- name: Création du premier utilisateur
  ignore_errors: yes
  uri:
    status_code: 201
    url: '{{ BOT_URL }}/api/user/admin'
    method: POST
    body_format: json
    body:
      email: '{{ USER_BOT_EMAIL }}'
      firstName: '{{ USER_BOT_FIRSTNAME }}'
      lastName: '{{ USER_BOT_LASTNAME }}'
      password: '{{ USER_BOT_PASSWORD }}'

- name: Login avec cet utilisateur
  uri:
    status_code: 201
    url: '{{ BOT_URL }}/api/auth/login'
    method: POST
    body_format: json
    body:
      email: '{{ USER_BOT_EMAIL }}'
      password: '{{ USER_BOT_PASSWORD }}'
  register: login
