- name: ensure user is present
  become: yes
  user:
    name: chatbot_user
    append: yes
    groups: wheel
    password: "{{ USER_PASSWORD | password_hash('sha512') }}"

## TRANSFERT ET INSTALLATIONS DES PAQUETS SYSTEME ET PYTHONS

- name: Transfert des paquets au serveur du Chatbot
  become: true
  copy:
    src: '../packages'
    dest: '{{ userBotDir }}/chatbot'

- name: Installation des paquets rpm requis
  become: true
  shell: 'dnf -y localinstall {{ userBotDir }}/chatbot/packages/*.rpm --allowerasing --skip-broken --disablerepo=*'

- name: Transfert du dossier au serveur du Chatbot
  become: true
  synchronize:
    src: '../chatbot'
    dest: '{{ userBotDir }}'

- name: Installation des paquets npm requis
  become: true
  shell: 'npm install -g {{ userBotDir }}/chatbot/node_modules/*.tgz --prefer-offline --cache {{ userBotDir }}/chatbot/.npm'

- name: Mise à jour de pip
  become: true
  shell: 'pip3 install --no-index --find-links {{ userBotDir }}/chatbot/python-packages pip==21.3.1'

- name: Installation des paquets python requis
  become: true
  shell: 'pip3 install --no-index --find-links {{ userBotDir }}/chatbot/python-packages rasa psycopg2-binary ansible'

- name: Ajout du chemin pour utiliser les raccourcis python
  become: true
  shell: 'export PATH=/usr/local/bin:$PATH'

## SECURISATION DE L'ACCES SSH ET CONFIGURATION DU PARE FEU

- name: Interdiction de l'accès ssh à l'utilisateur root
  become: yes
  lineinfile:
    line: PermitRootLogin no
    dest: /etc/ssh/sshd_config
    regexp: ^PermitRootLogin

- name: Configuration du pare-feu
  become: yes
  ufw:
    policy: deny
    state: enabled

- name: Open port ssh
  become: yes
  ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Open port 443
  become: yes
  ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Open port 80
  become: yes
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Open port 5005
  become: yes
  ufw:
    rule: allow
    port: '5005'
    proto: tcp

## CONFIGURATION DE NGINX

- name: Copie du fichier de config nginx
  copy:
    src: 'roles/chatbotPrebook/files/nginx_rhel.conf'
    dest: '/etc/nginx/nginx.conf'
  become: yes

- name: Set right rights on www directory
  become: true
  file:
    path: '{{appsDir}}'
    owner: 'chatbot_user'
    group: wheel
    mode: '775'
    recurse: yes

- name: Copie de la configuration du site statique nginx
  copy:
    src: 'roles/chatbotPrebook/files/nginx_conf.cfg'
    dest: '/etc/nginx/conf.d/default.conf'
  become: yes

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes

- name: setenforce permissive
  become: true
  shell: 'setenforce permissive'
