- name: Do not allow root access via ssh
  become: true
  ansible.builtin.lineinfile:
    line: PermitRootLogin no
    dest: /etc/ssh/sshd_config
    regexp: ^PermitRootLogin

- name: Delete ssh host keys
  become: true
  ansible.builtin.shell: "rm /etc/ssh/ssh_host_* && dpkg-reconfigure openssh-server"
  notify: restart ssh
  when: renew_ssh is defined and renew_ssh == "yes"

- name: UFW pour OS Debian
  include_tasks: debian.yml
  when: ansible_distribution == 'Debian'
