- name: "Ne pas autoriser l'accès root via ssh"
  become: yes  
  lineinfile:
    line: PermitRootLogin no
    dest: /etc/ssh/sshd_config
    regexp: ^PermitRootLogin

# - name: "Supprimer les clés d'hôte ssh"
#   become: yes
#   shell: "rm /etc/ssh/ssh_host_* && dpkg-reconfigure openssh-server"
#   notify: restart ssh
#   when: renew_ssh is defined and renew_ssh == "yes"

# - name: "Supprimer le fichier de verrouillage apt"
#   file:
#     state: absent
#     path: "/var/lib/dpkg/lock"

- name: "Vérifier que ufw est installé" 
  become: yes 
  apt:
    name: ufw

- name: "Configuration du pare-feu" 
  become: yes 
  ufw:
    policy: deny
    state: enabled

- name: "Ouverture port ssh"
  become: yes 
  ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: "Ouverture port 443"
  become: yes 
  ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: "Ouverture port 80"
  become: yes 
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: "Ouverture port 5005"
  become: yes 
  ufw:
    rule: allow
    port: '5005'
    proto: tcp

- name: "Ouverture port DB"
  become: yes 
  ufw:
    rule: allow
    port: '{{ db_port }}'
    proto: tcp
