- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: 'yes'
    update_cache: 'yes'

- name: Install dependencies for nodejs
  become: yes
  apt:
    pkg:
      - curl
      - software-properties-common

- name: Install the gpg key for nodejs LTS
  become: yes
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs LTS repos
  become: yes
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install last Nginx version
  include_role:
    name: nginx

- name: Install required dependencies (python, ssl, postgresql, node ...)
  become: true
  apt:
    pkg:
      - python3-pip
      - libssl-dev
      - bash
      - openssl
      - python3-dev
      - python-setuptools
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python3-psycopg2
      - acl
      - nodejs
      - git
      - curl
      - screen
      - rsync
      - certbot
      - snapd

- name: copy the nginx config file
  copy:
    src: 'roles/chatbotGeneration/files/nginx.conf'
    dest: '/etc/nginx/nginx.conf'
  become: yes

- name: Set right rights on www directory - Debian
  become: true
  file:
    path: '{{appsDir}}'
    group: www-data
    mode: '774'
    recurse: yes
