- name: Configuration pour OS Debian
  include_tasks: debian.yml
  when: ansible_distribution == 'Debian'

- name: Configuration pour OS RHEL 8 & CentOS 8 - Internet
  include_tasks: rhel.yml
  when: (ansible_distribution == 'CentOS' or ansible_distribution == "RedHat") and (intranet is not defined or intranet == "false")

- name: Configuration pour OS RHEL 8 & CentOS 8 - Intranet
  include_tasks: rhel_intranet.yml
  when: (ansible_distribution == 'CentOS' or ansible_distribution == "RedHat") and (intranet is defined and intranet == "true")

- name: Install last version of pip
  become: true
  when: intranet is not defined or intranet == "false"
  pip:
    executable: pip3
    name: pip
    extra_args: -U

- name: Install RASA & Ansible
  become: true
  when: intranet is not defined or intranet == "false"
  pip:
    executable: pip3
    name:
      - rasa==2.8.7
      - psycopg2-binary
      - ansible

- name: NODE | Install pm2
  become: yes
  when: intranet is not defined or intranet == "false"
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Ensure the PostgreSQL service is running - Internet
  when: intranet is not defined or intranet == "false"
  become: yes
  service:
    name: 'postgresql'
    state: 'started'
    enabled: 'yes'

- name: Ensure database is created
  become: true
  become_user: postgres
  postgresql_db:
    name: 'rasa'
    encoding: 'UTF-8'
    #        conn_limit: '100'
    state: 'present'
    template: 'template0'

- name: Adds unaccent extension
  become: true
  become_user: postgres
  postgresql_ext:
    name: unaccent
    db: rasa

- name: Ensure user has access to the database
  become: true
  become_user: postgres
  postgresql_user:
    db: 'rasa'
    name: 'rasa_user'
    password: '{{ DB_PASSWORD }}'
    priv: 'ALL'
    state: 'present'

- name: Ensure user does not have unnecessary privileges
  become: true
  become_user: postgres
  postgresql_user:
    name: 'rasa_user'
    role_attr_flags: 'NOSUPERUSER,NOCREATEDB'
    state: 'present'

- name: Copie de la configuration du site statique nginx
  copy:
    src: 'roles/chatbotGeneration/files/nginx_conf.cfg'
    dest: '/etc/nginx/conf.d/default.conf'
  become: yes

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
