---
- name: Configuration pour OS Debian
  ansible.builtin.include_tasks: debian.yml
  when: ansible_distribution == 'Debian'

- name: Configuration pour OS RHEL 8 & Almalinux 8
  ansible.builtin.include_tasks: rhel.yml
  when: (ansible_distribution == 'RedHat' or ansible_distribution == 'AlmaLinux')

- name: "Ajouter /app/rasa/bin au PATH de l'utilisateur {{ chatbot_user }}"
  ansible.builtin.lineinfile:
    path: "/home/{{ chatbot_user }}/.bashrc"
    line: 'export PATH="{{ app_venv_folder }}/bin:$PATH"'
    create: true
  become: true
  become_user: "{{ chatbot_user }}"

- name: Copie de la configuration du site statique nginx
  ansible.builtin.copy:
    src: 'roles/chatbotGeneration/files/nginx_conf.cfg'
    dest: '/etc/nginx/conf.d/default.conf'
  become: true
  notify:
    - Restart nginx
