- name: Copie du fichier de config nginx
  copy:
    src: 'roles/chatbotGeneration/files/nginx_rhel.conf'
    dest: '/etc/nginx/nginx.conf'
  become: yes

- name: Copie du fichier de config postgres
  copy:
    src: 'roles/chatbotGeneration/files/pg_hba.conf'
    dest: '/var/lib/pgsql/11/data/pg_hba.conf'
  become: yes

- name: Set right rights on www directory
  become: true
  file:
    path: '{{appsDir}}'
    owner: 'chatbot_user'
    group: wheel
    mode: '775'
    recurse: yes

- name: Ensure the PostgreSQL service is running
  become: yes
  service:
    name: 'postgresql-11'
    state: 'started'
    enabled: 'yes'
