---
- name: Update de Yum
  become: true
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: true

- name: Install des dépendances pour nodejs
  become: true
  ansible.builtin.dnf:
    name:
      - curl
      - gcc-c++
      - make

- name: Download NodeSource setup script for Node.js {{ nodejs_version }}
  ansible.builtin.get_url:
    url: "https://rpm.nodesource.com/setup_{{ nodejs_version }}.x"
    dest: "/tmp/setup_{{ nodejs_version }}.sh"
    mode: '0755'

- name: Execution du script NodeSource pour Node.js {{ nodejs_version }}
  become: true
  ansible.builtin.command: "/bin/bash /tmp/setup_{{ nodejs_version }}.sh"
  args:
    creates: /etc/yum.repos.d/nodesource-el8.repo

- name: Install Node.js "{{ nodejs_version }}"
  become: true
  ansible.builtin.package:
    name: "nodejs"
    state: present
    update_cache: true

- name: Vérification de la version de Node.js
  ansible.builtin.command:
    cmd: "node -v"
  register: node_version
  changed_when: false

- name: Affichage de la version de Node.js
  ansible.builtin.debug:
    msg: "Node.js version is {{ node_version.stdout }}"

- name: Activation du repo EPEL
  become: true
  ansible.builtin.package:
    name: epel-release
    state: present

- name: Installation des dépendances (python, ssl, postgresql, node ...)
  become: true
  ansible.builtin.dnf:
    name:
      - python3-pip
      - bash
      - openssl
      - postgresql-server
      - postgresql-contrib
      - python3-psycopg2
      - python3-certbot-nginx
      - acl
      - nodejs
      - git
      - nginx
      - screen
      - rsync
      - jq
      - acl

- name: Activer le service nginx au démarrage
  ansible.builtin.systemd:
    name: nginx
    enabled: true
  become: true

- name: Copie des fichiers nginx
  become: true
  ansible.builtin.copy:
    src: 'roles/chatbotGeneration/files/nginx_rhel.conf'
    dest: '/etc/nginx/nginx.conf'

- name: Ajout des ACLs pour pouvoir lancer en tant que "{{ chatbot_user }}"
  ansible.builtin.include_tasks: acl.yml

- name: Installation de python
  ansible.builtin.include_tasks: rhel_venv.yml

- name: Installation de pm2
  ansible.builtin.include_tasks: rhel_pm2.yml
