- name: Update and upgrade apt packages
  become: true
  dnf:
    name: '*'
    state: latest
    update_cache: 'yes'

- name: Install dependencies for nodejs
  become: yes
  dnf:
    name:
      - curl
      - gcc-c++
      - make

- name: NodeSource binary distribution
  command:
    cmd: 'curl -sL https://rpm.nodesource.com/setup_{{ NODEJS_VERSION }}.x'
    warn: false

- name: Install required dependencies (python, ssl, postgresql, node ...)
  become: true
  dnf:
    name:
      - python3-pip
      - bash
      - openssl
      - python3-psycopg2
      - acl
      - nodejs
      - git
      - nginx
      - screen
      - rsync
      - certbot
      - snapd
      - clamav

- name: copy the nginx config file
  copy:
    src: 'roles/chatbotGeneration/files/nginx_rhel.conf'
    dest: '/etc/nginx/nginx.conf'
  become: yes

- name: Création d'un dossier pour les fichiers infectés
  file:
    path: /root/quarantine
    state: directory
  become: yes

- name: Exclusion des répertoires spéciaux de linux pour l'antivirus
  command:
    cmd: 'printf "ExcludePath ^/proc\nExcludePath ^/sys\nExcludePath ^/run\nExcludePath ^/dev\nExcludePath ^/snap\nExcludePath ^/var/lib/lxcfs/cgroup\nExcludePath ^/root/quarantine\n" | sudo tee -a /etc/clamav/clamd.conf'
  become: yes

- name: restart antivirus
  service:
    name: clamav-daemon
    state: restarted
  become: yes

- name: Lancement d'un scan complet antivirus toutes les semaines
  command:
    cmd: 'echo "0 1 * * 0 root /usr/bin/clamdscan -m --fdpass --log=/var/log/clamav/clamdscan.log --move=/root/quarantine /" | tee /etc/cron.d/clamdscan'
  become: yes

- name: Set right rights on www directory - RHEL 8 & CentOS 8
  become: true
  file:
    path: '{{appsDir}}'
    group: wheel
    mode: '774'
    recurse: yes
