---
- name: Déployer le service pm2 avec un template Jinja
  become: true
  ansible.builtin.template:
    src: pm2-chatbotback.service.j2
    dest: /etc/systemd/system/pm2-{{ chatbot_user }}.service
    owner: root
    group: root
    mode: '0644'

- name: Déployer le service Rasa Core avec un template Jinja
  become: true
  ansible.builtin.template:
    src: rasa-core.service.j2
    dest: /etc/systemd/system/rasa-core.service
    owner: root
    group: root
    mode: '0644'

- name: Déployer le service Rasa Actions avec un template Jinja
  become: true
  ansible.builtin.template:
    src: rasa-actions.service.j2
    dest: /etc/systemd/system/rasa-actions.service
    owner: root
    group: root
    mode: '0644'

- name: Recharger le démon systemd
  become: true
  ansible.builtin.command: systemctl daemon-reload
  changed_when: false

- name: Vérification du statut de PM2
  command: systemctl is-active "pm2-{{ chatbot_user }}"
  register: pm2_is_active
  ignore_errors: true
  changed_when: false

- name: Démarrer PM2 si le statut n'est pas active
  become: true
  ansible.builtin.systemd:
    name: "pm2-{{ chatbot_user }}"
    state: started
    enabled: true
  when: pm2_is_active.stdout != "active"
  ignore_errors: true

- name: Activer les services Rasa Core et Actions
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: stopped
  loop:
    - rasa-core.service
    - rasa-actions.service
