---
- name: Tenter de créer l'utilisateur admin
  ansible.builtin.uri:
    url: "{{ BOT_URL }}/api/user/admin"
    method: POST
    body: |
      {
        "email": "{{ admin_email }}",
        "firstName": "{{ admin_firstname }}",
        "lastName": "{{ admin_lastname }}",
        "password": "{{ admin_password }}"
      }
    status_code: [201, 403, 500]  # 201 si création réussie, 403 si admin déjà existant
    body_format: json
  register: create_admin_response

- name: Vérifier si la création a échoué avec un code 500 mais que l'admin a été créé
  ansible.builtin.debug:
    msg: "Création de l'utilisateur admin"
  when: create_admin_response.status == 500

- name: Vérifier le message de la réponse
  ansible.builtin.debug:
    msg: "L'utilisateur addmin existe"
  when: create_admin_response.status == 403

- name: Login
  ansible.builtin.uri:
    url: "{{ BOT_URL }}/api/auth/login"
    method: POST
    body: |
      {
        "email": "{{ admin_email }}",
        "password": "{{ admin_password }}"
      }
    status_code: 201
    body_format: json
  register: login

- name: Set API-KEY
  ansible.builtin.uri:
    url: "{{ BOT_URL }}/api/config/api-key"
    method: POST
    headers:
      Authorization: "Bearer {{ login.json.chatbotToken }}"
    status_code: 201
  register: apiKey
