- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: 'yes'
    update_cache: 'yes'

- name: Install required dependencies (nginx, node, npm, certbot ...)
  become: true
  apt:
    pkg:
      - nginx
      - openssl

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes

- name: remove old angular app
  file:
    path: '{{ appsDir }}/{{ angularDir }}/'
    state: absent
  become: yes

- name: copy angular app
  copy:
    src: '{{ userDir }}/{{ angularDir }}/'
    dest: '{{ appsDir }}/{{ angularDir }}'
  become: yes
