- name: Changement de droits et de propriétaire pour le dossier www
  become: true
  file:
    path: '{{ appsDir }}'
    state: directory
    owner: '{{ ansible_user }}'
    mode: '775'

- name: Création du répertoire git
  become: true
  file:
    path: '{{ appsDir }}/{{ gitDir }}'
    state: directory
    owner: '{{ ansible_user }}'
    mode: '775'

- name: Clone du repo de l'Usine
  become: yes
  git:
    repo: https://github.com/fabnumdef/fabrique-chatbot.git
    dest: '{{ appsDir }}/{{ gitDir }}/{{ usineDir }}'
    force: yes
    version: '{{ usineBranch }}'

- name: Installation des paquets du front
  become: yes
  npm:
    path: '{{ appsDir }}/{{ gitDir }}/{{ usineDir }}/front'
    production: yes

- name: Build du front | PROD
  become: yes
  command:
    cmd: npm run build:prod
    chdir: '{{ appsDir }}/{{ gitDir }}/{{ usineDir }}/front'
