- name: Installation de yum pour télécharger les rpm
  become: yes
  apt:
    pkg:
      - yum
      - yum-plugin-downloadonly

- name: Téléchargement des paquets requis
  become: yes
  yum:
    download_only: yes
    download_dir: '{{ userDir }}/{{ intranetDir }}/packages'
    name:
      - python3-pip
      - bash
      - openssl
      - postgresql-server
      - postgresql-contrib
      - python3-psycopg2
      - acl
      - nodejs
      - git
      - nginx
      - screen
      - rsync
      - snapd
