- name: Téléchargement des paquets requis
  become: yes
  yum:
    download_only: yes
    download_dir: '{{ userDir }}/{{ intranetDir }}/packages'
    use_backend: 'dnf'
    name:
      - python3-pip
      - bash
      - openssl
      - postgresql-server
      - postgresql-contrib
      - python3-psycopg2
      - acl
      - nodejs
      - git
      - nginx
      - screen
      - rsync
      - snapd
