- name: npm install chatbot-front
  npm:
    path: '{{ appsDir }}/{{ gitDir }}/{{ frontDir }}'
  environment: 
    NODE_OPTIONS: '--max-old-space-size=3072'  

- name: npm install chatbot-front librairies
  npm:
    path: '{{ appsDir }}/{{ gitDir }}/{{ frontDir }}/projects/ngx-rasa-webchat'

- name: npm build chatbot-front
  command:
    cmd: npm run build:prod
    chdir: '{{ appsDir }}/{{ gitDir }}/{{ frontDir }}'