---
- name: Mise à jour des repos des Chatbots dans l'Usine
  hosts: localhost
  remote_user: fab_user
  vars_files:
    - roles/vars/main.yml
    - roles/vars/usine.yml

  roles:
    - usineUpdaterepos
