---
# ansible-playbook playUsinesecurity.yml -i $IP_ADRESS, -e "USER_PASSWORD='$USER_PASSWORD'";
- name: Sécurité de l'Usine à Chatbots
  hosts: all
  remote_user: ansible

  vars_files:
    - roles/vars/main.yml
    - roles/vars/credentials.yml

  vars:
    - DB_PORT: "20184"

  roles:
    - usineSecurity

  handlers:
    - name: restart ssh
      become: yes
      service:
        name: ssh
        state: restarted
