---
- name: Génération d'un Chatbot
  hosts: all
  remote_user: chatbot_user
  vars_files:
    - roles/vars/main.yml
    - roles/chatbotGeneration/files/credentials.yml
  roles:
    - chatbotGeneration
