---
- name: Mise à jour des repos des Chatbots dans l'Usine
  # Changer host lors de l'installation
#  hosts: all
  hosts: localhost
  remote_user: ansible

  vars_files:
    - roles/vars/main.yml
    - roles/vars/credentials.yml

  roles:
    - usineUpdaterepos
