---
# ansible-playbook playChatbot.yml -i $IP_ADRESS, -e '{USER_PASSWORD: '$USER_PASSWORD', ROOT_USER: '$ROOT_USER', ROOT_PASSWORD: '$ROOT_PASSWORD', DB_PASSWORD: '$DB_PASSWORD', frontBranch: 'master', backBranch: 'master', botBranch: 'master', botDomain: '$URL_BOT', intranet: false}';

- import_playbook: playChatbotprebook.yml
- import_playbook: playChatbotsecurity.yml
- import_playbook: playChatbotconfiguration.yml
- import_playbook: playChatbotupdaterepos.yml
- import_playbook: playChatbotgeneration.yml
