---
# ansible-playbook playChatbotupdaterepos.yml -i $IP_ADRESS, -e '{USER_PASSWORD: '$USER_PASSWORD', frontBranch: 'master', backBranch: 'master', botBranch: 'master'}';

- name: Mise à jour des différents repos git + build des fronts si besoin
  hosts: localhost
  vars_files:
    - roles/vars/main.yml
    - roles/vars/credentials.yml
  roles:
    - updateRepos
