---
# ansible-playbook playUsinesecurity.yml -i $IP_ADRESS, -e "ansible_password='$USER_PASSWORD' ansible_become_pass='$USER_PASSWORD'";
- name: Sécurité de l'Usine à Chatbots
  hosts: all
  remote_user: fab_user

  vars:
    - DB_PORT: "20184"

  roles:
    - usineSecurity

  handlers:
    - name: restart ssh
      become: yes
      service:
        name: ssh
        state: restarted
