---
# ansible-playbook playChatbotprebook.yml -i $IP_ADRESS, -e '{USER_PASSWORD: '$USER_PASSWORD', ROOT_USER: '$ROOT_USER', ROOT_PASSWORD: '$ROOT_PASSWORD'}';

- name: Génération d'un Chatbot
  hosts: all
  remote_user: ansible
  vars_files:
    - roles/vars/main.yml

  vars:
    - ansible_user: "{{ ROOT_USER | default('debian') }}"
    - ansible_password: "{{ ROOT_PASSWORD }}"
    - ansible_become_pass: "{{ ROOT_PASSWORD }}"

  roles:
    - chatbotPrebook
