---
# ansible-playbook playChatbotprebook.yml -i $IP_ADRESS, -e '{USER_PASSWORD: '$USER_PASSWORD'}';

- name: Génération d'un Chatbot
  hosts: all
  remote_user: ansible
  vars_files:
    - roles/vars/main.yml

  vars:
    - ansible_user: "{{ ROOT_USER | default('ansible') }}"
#    - ansible_password: "{{ ROOT_PASSWORD | USER_PASSWORD }}"
    - ansible_become_pass: "{{ USER_PASSWORD }}"

  roles:
    - chatbotPrebook
