---

# Prerequisite:
#   ssh access with root and password
#   ssh authentication key on local machine

- hosts: dev
  vars_prompt:

    - name: root_password
      prompt: Enter new root password
      private: yes
      encrypt: sha512_crypt
      confirm: yes
      salt_size: 7

    - name: user_password
      prompt: Enter new user password
      private: yes
      encrypt: sha512_crypt
      confirm: yes
      salt_size: 7

    - name: ssh_key
      prompt: Enter filename of public ssh key
      default: "~/.ssh/id_rsa.pub"
      private: no


  remote_user: root


  tasks:

    - name: apply root password
      user:
        name: root
        password: "{{ root_password }}"

    - name: ensure sudo is installed
      apt:
        name: sudo

    - name: ensure user is present
      user:
        name: fab_user
        append: yes
        groups: sudo
        password: "{{ user_password }}"

    - name: ensure user is accessable with ssh key
      authorized_key:
        user: fab_user
        key: "{{ lookup('file', '{{ ssh_key }}') }}"
