- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: 'yes'

- name: Install dependencies for nodejs
  become: yes
  apt:
    pkg:
      - curl
      - software-properties-common

- name: Install the gpg key for nodejs LTS
  become: yes
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs LTS repos
  become: yes
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION_USINE }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install last Nginx version
  include_role:
    name: nginx

- name: Install required dependencies (nginx, node, npm ...)
  become: yes
  apt:
    pkg:
      - python-setuptools
      - build-essential
      - nodejs
      - acl
      - libpq-dev
      - python3-psycopg2
      - python-psycopg2
      - git
      - rsync
      - sshpass
      - certbot
      - python-certbot-nginx
      - redis-server
      - python-pip
      - python3-venv
      - python3-pip
      - clamav
      - clamav-daemon

- name: Création d'un dossier pour les fichiers infectés
  file:
    path: /root/quarantine
    state: directory
  become: yes

- name: Exclusion des répertoires spéciaux de linux pour l'antivirus
  command:
    cmd: 'printf "ExcludePath ^/proc\nExcludePath ^/sys\nExcludePath ^/run\nExcludePath ^/dev\nExcludePath ^/snap\nExcludePath ^/var/lib/lxcfs/cgroup\nExcludePath ^/root/quarantine\n" | sudo tee -a /etc/clamav/clamd.conf'
  become: yes

- name: restart antivirus
  service:
    name: clamav-daemon
    state: restarted
  become: yes

- name: Lancement d'un scan complet antivirus toutes les semaines
  command:
    cmd: 'echo "0 1 * * 0 root /usr/bin/clamdscan -m --fdpass --log=/var/log/clamav/clamdscan.log --move=/root/quarantine /" | tee /etc/cron.d/clamdscan'
  become: yes
