- name: Update and upgrade dnf packages
  become: true
  dnf:
    name: '*'
    state: latest
    update_cache: 'yes'

- name: Install dependencies for nodejs
  become: yes
  dnf:
    name:
      - curl
      - gcc-c++
      - make

#- name: Enable node 12
#  become: yes
#  command:
#    cmd: 'yes | dnf module enable nodejs:12'

#- name: Enable postgres 11
#  become: yes
#  command:
#    cmd: 'yes | dnf module enable postgresql:11'

- name: Install required dependencies (python, ssl, postgresql, node ...)
  become: true
  dnf:
    name:
      - python3-pip
      - bash
      - openssl
      - postgresql-server
      - postgresql-contrib
      - python3-psycopg2
      - acl
      - nodejs
      - git
      - nginx
      - screen
      - rsync
      - snapd
      - clamav-daemon

- name: Install Certbot
  include_role:
    name: certbot

- name: Init DB cluster
  become: yes
  ignore_errors: yes
  command:
    cmd: 'postgresql-setup --initdb'

# WARNING POSTGRES ON CENTOS ident to md5
# setenforce permissive

