- name: Start snapd
  become: yes
  systemd:
    name: snapd.socket
    state: started

- name: Enable snap
  become: yes
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link

- name: Install certbot
  become: yes
  snap:
    classic: yes
    name: certbot

- name: Enable certbot
  become: yes
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
