name: Build & Deploy
on:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set env to dev
        if: endsWith(github.ref, '/develop')
        run: |
          echo "::set-env name=ENVIRONMENT::dev"
      - name: Set env to prod
        if: endsWith(github.ref, '/master')
        run: |
          echo "::set-env name=ENVIRONMENT::prod"

      - uses: actions/checkout@v1

      - uses: haya14busa/action-cond@v1
        id: host
        with:
          cond: ${{ github.ref == '/master' }}
          if_true: '51.91.100.194'
          if_false: '51.254.201.98'

      - name: copy app via ssh key
        uses: appleboy/scp-action@master
        env:
          HOST: '${{ steps.host.outputs.value }}'
          USERNAME: fab_user
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "./"
          target: "~/fabrique-chatbot-back/"
          strip_components: 1
          timeout: 240s

      - name: copy ansible scripts via ssh key
        uses: appleboy/scp-action@master
        env:
          HOST: '${{ steps.host.outputs.value }}'
          USERNAME: fab_user
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "./ansible/"
          target: "~/fabrique-chatbot-back/"
          timeout: 120s

      - name: launch deploy ansible script
        uses: appleboy/ssh-action@master
        env:
          HOST: '${{ steps.host.outputs.value }}'
          USERNAME: fab_user
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          script: |
            rm -rf ~/fabrique-chatbot-back/ansible/fabrique/password_file
            cat >> ~/fabrique-chatbot-back/ansible/fabrique/password_file << 'END'
            ${{ secrets.VAULT_PASSWORD }}
            END
            ansible-vault decrypt --vault-id dev@~/fabrique-chatbot-back/ansible/fabrique/password_file ~/fabrique-chatbot-back/ansible/fabrique/.env
            ansible-playbook ~/fabrique-chatbot-back/ansible/fabrique/backserver.yml --vault-id dev@~/fabrique-chatbot-back/ansible/fabrique/password_file

      - name: delete tmp dir
        uses: appleboy/ssh-action@master
        env:
          HOST: '${{ steps.host.outputs.value }}'
          USERNAME: fab_user
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          script:
            rm -rf ~/fabrique-chatbot-back
