name: Build & Deploy
on:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set env to dev
        if: endsWith(github.ref, '/develop')
        run: |
          echo "::set-env name=ENVIRONMENT::dev"
      - name: Set env to prod
        if: endsWith(github.ref, '/master')
        run: |
          echo "::set-env name=ENVIRONMENT::prod"

      - uses: actions/checkout@v1

      - uses: haya14busa/action-cond@v1
        id: host
        with:
          cond: ${{ env.ENVIRONMENT == 'prod' }}
          if_true: ${{ secrets.PROD_IP }}
          if_false: ${{ secrets.DEV_IP }}

      - uses: haya14busa/action-cond@v1
        id: user_password
        with:
          cond: ${{ env.ENVIRONMENT == 'prod' }}
          if_true: ${{ secrets.PROD_USER_PASSWORD }}
          if_false: ${{ secrets.DEV_USER_PASSWORD }}

      - uses: actions/setup-node@v1 #this installs node and npm for us
        with:
          node-version: '10.x'

      - uses: actions/cache@v1 # this allows for re-using node_modules caching, making builds a bit faster.
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install #TODO: --only-prod, le build crash à voir pq
      - run: npm install -g @angular/cli > /dev/null

      - run: npm run build:dev
        if: ${{ env.ENVIRONMENT != 'prod' }}

      - run: npm run build:prod
        if: ${{ env.ENVIRONMENT == 'prod' }}

      - name: copy app via ssh key
        uses: appleboy/scp-action@master
        env:
          HOST: '${{ steps.host.outputs.value }}'
          USERNAME: fab_user
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "./dist/fabrique-chatbot-front/"
          target: "~/fabrique-chatbot-front/"
          strip_components: 3
          timeout: 240s

      - name: copy ansible scripts via ssh key
        uses: appleboy/scp-actioter
        env:
          HOST: '${{ steps.host.outputs.value }}'
          USERNAME: fab_user
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "./ansible/"
          target: "~/fabrique-chatbot-front/"
          timeout: 120s

      - name: launch ansible script
        uses: appleboy/ssh-action@master
        env:
          HOST: '${{ steps.host.outputs.value }}'
          USERNAME: fab_user
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USER_PASSWORD: '${{ steps.user_password.outputs.value }}'
        with:
          envs: USER_PASSWORD
          script: |
            ansible-playbook ~/fabrique-chatbot-front/ansible/frontserver.yml -e "user_password=$USER_PASSWORD"
            rm -rf ~/fabrique-chatbot-front
