name: Build & Deploy
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set env to dev
        if: endsWith(github.ref, '/develop')
        run: |
          echo "::set-env name=ENVIRONMENT::dev"
      - name: Set env to preprod
        if: endsWith(github.ref, '/master')
        run: |
          echo "::set-env name=ENVIRONMENT::preprod"

      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1 #this installs node and npm for us
        with:
          node-version: '10.x'

      - uses: actions/cache@v1 # this allows for re-using node_modules caching, making builds a bit faster.
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: copy app via ssh key
        uses: appleboy/scp-action@master
        env:
          HOST: 51.254.201.98
          USERNAME: fab_user
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "./"
          target: "~/fabrique-chatbot-back/"
          strip_components: 1
          timeout: 240s

      - name: copy ansible scripts via ssh key
        uses: appleboy/scp-action@master
        env:
          HOST: 51.254.201.98
          USERNAME: fab_user
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "./ansible/"
          target: "~/fabrique-chatbot-back/"
          timeout: 120s

      - name: launch ansible script
        uses: appleboy/ssh-action@master
        env:
          HOST: 51.254.201.98
          USERNAME: fab_user
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          script: |
            cat >> ~/fabrique-chatbot-back/ansible/fabrique/password_file << 'END'
            ${{ secrets.VAULT_PASSWORD }}
            END
            ansible-vault decrypt --vault-id dev@~/fabrique-chatbot-back/ansible/fabrique/password_file ~/fabrique-chatbot-back/ansible/fabrique/.env
            ansible-playbook ~/fabrique-chatbot-back/ansible/fabrique/backserver.yml --vault-id dev@~/fabrique-chatbot-back/ansible/fabrique/password_file
            rm -rf ~/fabrique-chatbot-back
